LINE_IF = 1
LINE_ELSE = 2
LINE_ELIF = 4
LINE_END = 8
LINE_MARCO = 16
LINE_COMMENT = 32
LINE_BLOCK = 64
LINE_FOR = 128
LINE_PASTE = 256
LINE_TEXT = 512
EOF_TEXT = 1024

ALWAYS_ALLOWED = LINE_IF | LINE_MARCO | LINE_PASTE | LINE_TEXT | LINE_COMMENT | LINE_FOR | LINE_BLOCK

MAP_LINE_TYPE = {
    None: LINE_TEXT,
    'if': LINE_IF,
    'else': LINE_ELSE,
    'elif': LINE_ELIF,
    'end': LINE_END,
    'for': LINE_FOR,
    'macro': LINE_MARCO,
    'block': LINE_BLOCK,
    '': LINE_COMMENT
}
